apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2	#/$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: calculator.local
    http:
      paths:
      - path: /api/(/|$)(.*)     #/api/register
        pathType: ImplementationSpecific			#Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /(.*)
        pathType: ImplementationSpecific #Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
